### ISSUE TITLE
Instant Run restarts entire app when ProcessPhoenix is included in a build

### ISSUE THREAD

**Issue by franklinharper** [JakeWharton/ProcessPhoenix#16]
Without ProcessPhoenix, only the current Activity is restarted. That saves developers a lot of time, because they don't have to navigate back to the Activity they're working on every time they make a change to the code.

The message from Instant Run is:

> Instant  Run applied code changes and restarted the app.
> The app was restarted since it uses multiple processes.

I realize that ProcessPhoenix might not be able to provide a solution to this problem.

My workaround was to remove ProcessPhoenix from our builds.

**Comment by JakeWharton** [comment]
I tried doing this in a single process when I first started but it wasn't working on some older OSs. I can try again at some point to see whether it can be pulled off, but for the time being probably best to remove it.

**Comment by roys** [comment]
Maybe there are other more elegant solutions, but I ended up using reflection to both easily keep ProcessPhoenix in the release build and still have Instant Run during development: https://stackoverflow.com/a/44932071/467650

**Comment by ScottPierce** [comment]
This still is an issue with process phoenix. It blocks instant run. Having to work around this by just not using process phoenix. @JakeWharton Any chance there will ever be a fix for this?

**Comment by masc3d** [comment]
wrapped it into a library which includes process phoenix as a `compileOnly` dependency works for me.

```kotlin
/**
 * Wrapper for process pheonix which allows calling
 * when included as a `releaseImplementation` dependency.
 *
 * As having process phoenix as an `implementation` dependency breaks instant run.
 * https://github.com/JakeWharton/ProcessPhoenix/issues/16
 *
 * Created by masc on 09.09.18.
 */
object ProcessPhoenix {
    fun triggerRebirth(context: Context, vararg nextIntents: Intent) {
        ProcessPhoenix.triggerRebirth(
            context,
            *nextIntents
        )
    }
}
```

consumer code

```kotlin
/**
 * Restart application
 * @param clean clean restart
 */
fun restart(clean: Boolean = false) {
    try {
        ProcessPhoenix.triggerRebirth(
            this,
            ...
        )
    } catch (e: NoClassDefFoundError) {
        throw IllegalStateException("Process phoenix is not available in debug builds as it breaks instant run", e)
    }
}
```

**Comment by masc3d** [comment]
is this still an issue with [apply changes](https://developer.android.com/studio/preview/features#apply-changes)?

**Comment by Kisty** [comment]
A no-op artifact would do the trick, like [Leak Canary](https://github.com/square/leakcanary/tree/master/leakcanary-android-no-op). Is there a no-op generator out there? Or perhaps just make a lightweight artifact manually.

e.g.
```
releaseImplementation 'com.jakewharton:process-phoenix:2.0.0'
debugImplementation 'com.jakewharton:process-phoenix-noop:2.0.0'
```

**Comment by JakeWharton** [comment]
The library is only for use in debug builds so that doesn't make sense.

**Comment by Kisty** [comment]
The use-case we have to restart the app in prod is to switch Fabric in-app tracking on and off because there's no Fabric API to switch it off when it's already on so we trigger a restart on the main menu Activity.

**Comment by JakeWharton** [comment]
Going to close and assume this isn't a problem with apply changes. Feel free to open a new issue if it is, although there's not much to be done here even if it is.
