### ISSUE TITLE
API 14

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/ProcessPhoenix#2]
I know, I don't like it either. We have 900,000 users on it though :(. Just tossing this up for consideration, completely understand if you'd rather not.

**Comment by JakeWharton** [comment]
It should be 3, not 14. There's nothing interesting in this library. You have a million users on API 14 (not 15)?!?

**Comment by hzsweers** [comment]
3 works too!

Yup. ~~Perks~~ curse of being bundled on Samsung devices.

**Comment by hzsweers** [comment]
3 works too!

Yup. ~~Perks~~ Curse of being bundled on Samsung devices.

**Comment by hzsweers** [comment]
Thanks!
