### ISSUE TITLE
Issue with activity stack when restarting with an intent.

### ISSUE THREAD

**Issue by sadegh** [JakeWharton/ProcessPhoenix#22]
Consider this change to the sample app:

Define `LaunhcerActivity` which is the launcher activity and it opens `MainActivity` inside of its `onCreate()`.
Change `restartWithIntent()` so that it creates intent with `LaunhcerActivity` class.

Now after clicking on `RESTART PROCESS WITH INTENT` button, it opens `LaunhcerActivity` then `LaunhcerActivity` opens `MainActivity`. Now if you press back you will see `LaunhcerActivity`, which is expected, but if you press back again, you will see another `MainActivity`.

It seems this is happening because `triggerRebirth(Context context, Intent... intents)` does not set `FLAG_ACTIVITY_NEW_TASK` and `FLAG_ACTIVITY_CLEAR_TASK` flags.

**Comment by sadegh** [comment]
I changed sample and and pushed the code [Here](https://github.com/sadegh/ProcessPhoenix/tree/sk/sample_2).

Here is a video of app's behavior.
![process_phoenix](https://user-images.githubusercontent.com/657684/33064896-80980ac2-cebc-11e7-98d1-ebba648447a4.gif)

**Comment by consp1racy** [comment]
When you supply your own intents you're responsible for their flags. I understand current behavior and can get behind it. I'm sure there are cases where you don't want the CLEAR_TOP flag. That being said, thanks for bringing this to my attention 👍
