### ISSUE TITLE
Application not restart in oreo and Pie

### ISSUE THREAD

**Issue by Dharmesh7197** [JakeWharton/ProcessPhoenix#30]

**Comment by shivam0x** [comment]
Have you added this intent filter to your launching activity?

           <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

You might be missing:
`<category android:name="android.intent.category.DEFAULT" />`

**Comment by parohy** [comment]
I think this can be marked as resolved in favour of [this issue](https://github.com/JakeWharton/ProcessPhoenix/issues/38) 🦄

**Comment by JakeWharton** [comment]
Yep, and the fix landed (...in 2017) and will be released soon.
