### ISSUE TITLE
Release of new version

### ISSUE THREAD

**Issue by auchri** [JakeWharton/ProcessPhoenix#31]
Hi,
thanks for this library!

Can you release a new version with the changes of this commit: https://github.com/JakeWharton/ProcessPhoenix/commit/6aa3479f6e05e3cd47c83bcfd0d34f47c65be7cd ?

The previous code which tries to find the launch intent does not work (for me) and throws the `IllegalStateException`, because it finds nothing.

(I get this error if I use  `implementation 'com.jakewharton:process-phoenix:2.0.0'`, it works with using `implementation 'com.jakewharton:process-phoenix:2.0.1-SNAPSHOT'`)

Thanks!

**Comment by cnordvik** [comment]
Hi @auchri , 

Adding `<category android:name="android.intent.category.DEFAULT" />` to the launcher activity solved that issue for me at least.

**Comment by auchri** [comment]
Of course my default activity has this:
![image](https://user-images.githubusercontent.com/5092164/51614695-7a256480-1f26-11e9-8a89-be5c29dd8bd5.png)

**Comment by drakeet** [comment]
+1

**Comment by henriquenfaria** [comment]
I can confirm that adding ` <category android:name="android.intent.category.DEFAULT" />` fixes the problem for me.

**Comment by JakeWharton** [comment]
Releasing soon
