### ISSUE TITLE
android:exported="true"

### ISSUE THREAD

**Issue by mhrohani1385** [JakeWharton/ProcessPhoenix#43]
this library manifest file have :

```xml
    <application>
        <activity
            android:name="com.jakewharton.processphoenix.ProcessPhoenix"
            android:process=":phoenix"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
    </application>
```

and im get this error on build project : android:exported needs to be explicitly specified

add this attribute in activity tag to fix error .

thanks

**Comment by mhrohani1385** [comment]
this is a proposal . not create an error .

**Comment by jobhh** [comment]
This is a requirement starting from Android 12 (SDK level 31). Quickfix for now is to set the target SDK level of your application to 30.
