### ISSUE TITLE
2.1.2 TriggerRebirth is not actually completely killing the app and restarting (Android 12). Works on 2.0.0

### ISSUE THREAD

**Issue by laurenyew-nytimes** [JakeWharton/ProcessPhoenix#51]
Noticed 2.1.2 isn't completely restarting the app from scratch. When I use `triggerRebirth(applicationContext)`, app is crashed and closed, but it's still running in the background. 2.0.0 doesn't have this issue and I'm running an Android 12 device.

I'm relying on triggerRebirth to fully restart my app so that some of my dagger setup / etc will get redone.
Can someone look into this?

**Comment by JakeWharton** [comment]
Isn't this already tracked by #47?
